[package]
name = "ember-ext-auth"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
ember-core = { path = "../../ember-core" }
jsonwebtoken = "9"
serde = { version = "1", features = ["derive"] }
