[package]
name = "ember-ext-runtime"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tracing = "0.1"
ember-ext-http = { path = "../ember-ext-http" }
ember-ext-exceptions = { path = "../ember-ext-exceptions" }
